baseURL = "https://mikitakhurana.github.io/"
languageCode = "en-us"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Research"
  URL = "#research"
  weight = 3

  [[menu.header]]
  name = "Teaching"
  URL = "#teaching"
  weight = 4

  [[menu.header]]
  name = "Education"
  URL = "#education"
  weight = 5


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Research"
  URL = "#research"
  weight = 3

  [[menu.footer]]
  name = "Teaching"
  URL = "#teaching"
  weight = 4

  [[menu.footer]]
  name = "Education"
  URL = "#education"
  weight = 5


[params]

  sections = ["showcase", "about", "conferences", "experience", "education", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "G-VMVXMZYG76" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Mikita"
    text2 = "Khurana"

  [params.footer]
      copyright = ""
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"